global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'emailaddress'
  smtp_auth_username: 'app-username'
  smtp_auth_password: 'app-password'
  smtp_require_tls: true

route:
  receiver: 'gmail-alerts'

receivers:
  - name: 'gmail-alerts'
    email_configs:
      - to: 'destination-emailaddress'